### ISSUE TITLE
Setting metatable on produced usertype table

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/sol2#75]
This is not exactly an issue per-se, more like a question, but I'm hoping you'll be able to help me regardless.

What I've been trying to do is set a meta function in the metatable of a usertype produced type in order to achieve interoperability with some old scripts that were running under LuaBind bindings.

More specifically, I want to set the `__call` metamethod to constructfunc so I can instantiate usertypes in lua-land as such `local x = usertype()` (instead of `local x = usertype.new()`). So far I've avoided using the raw Lua C API for this, since I assume (from what I've seen) that you perform some sort of cleanup on user defined types.

All my attempts so far (using Sol2 methods) have resulted in adding the function to the actual table members, and not its metatable, so I'm kinda stuck.

Thanks in advance.

**Comment by ThePhD** [comment]
Got it working with a test program, but we do need some kind of useful way of making it easier to transition to luabind. I need to add something to the `usertype` maker to allow for this syntax to be a thing. What do we call the key?

````
lua.new_usertype<thing>( "thing",
     ????, sol::constructors< /*...*/ >()
);
````

It would be nice to find out what `????` would be called.

**Comment by ThePhD** [comment]
Until such a time, here's the example:

````
#define SOL_CHECK_ARGUMENTS

#include "sol.hpp"
#include <iostream>

struct thing {
	int v = 100;

	thing() {}
	thing(int x) : v(x) {}
};

int main(int argc, char* const argv[]) {
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	lua.new_usertype<thing>("thing",
		"v", &thing::v
	);
	

	sol::table thingtable = lua["thing"];
	thingtable[sol::metatable_key] = lua.create_table();
	sol::table metathingtable = thingtable[sol::metatable_key];
	auto thingtype = thingtable.get_type();
	auto metathingtype = metathingtable.get_type();
	metathingtable["__call"] = []( sol::stack_reference src ) {
		return thing(52);
	};

	lua.script(R"(
	t = thing()
)");

	thing& y = lua["t"];
	std::cout << y.v << std::endl;
	
	return 0;
}
````

**Comment by OrfeasZ** [comment]
Maybe something like `sol::??::call_constructor`?

**Comment by ThePhD** [comment]
`sol::function_call_constructor` might be more explicit... albeit it iiis long... `sol::call_constructor` is probably good.

**Comment by OrfeasZ** [comment]
By the way, random question: Does omitting `sol::constructor<>` prevent a user from instantiating a usertype in lualand?

**Comment by ThePhD** [comment]
`sol` automatically checks if a type is default constructible. If it is, it will generate `sol::default_constructor` for you and bind it to `new`.

**Comment by ThePhD** [comment]
`sol::function_operator_constructor` will probably be a thing.

**Comment by OrfeasZ** [comment]
Even though I haven't had a chance to test it yet, thanks for implementing this and #78 so promptly! You're awesome.

**Comment by ThePhD** [comment]
Get it here: https://github.com/ThePhD/sol2/releases/tag/v2.5.3

**Comment by adriweb** [comment]
I didn't really want to open a new issue for this considering this one is similar enough...

I'm creating usertypes with classes that have multiple constructors. Everything seems to work fine so far.
Now, I've wondered about skipping the `Foo.new(...)` to just be able to do `Foo(...)`, but I'm not sure how to do it from sol directly in a clean way (`call_constructor` requires _a_ constructor, but I have several...), rather than just setting `meta.__call = Foo.new` (which appears to work fine as well, from testing quickly).
Any idea?

**Comment by OrfeasZ** [comment]
@adriweb I've been using `sol::call_constructor` and multiple constructors without any issues. Syntax is the same as using a named constructor.

Take this class for example:
```cpp
class SomeClass
{
    SomeClass(int);
    SomeClass(const std::string&);
    SomeClass(bool);
}
```

The way you would bind its constructors would be as follows:
```cpp
lua.new_usertype<SomeClass>("SomeClass",
    sol::call_constructor, sol::constructors<sol::types<int>, sol::types<const std::string&>, sol::types<bool>>(),
    ...
);
```

With the changes introduced in #362 you should also be able to specify it like this (granted you're using the latest and greatest version):
```cpp
lua.new_usertype<SomeClass>("SomeClass",
    sol::call_constructor, sol::constructors<void(int), void(const std::string&), void(bool)>(),
    ...
);
```

**Comment by adriweb** [comment]
Hmm, then I guess something else around the construction is going wrong (causing the exception to be thrown), I'll try to dig in more.

(And yep I have the latest version, I guess I'll use the new syntax everywhere!)

Thanks

**Comment by ThePhD** [comment]
As a side note, I haven't updated the `single/sol.hpp` just yet in the repo.

**Comment by adriweb** [comment]
Well well well... updating to the latest single.hpp (from a few days ago's to yesterday's) solved the exception I had, and everything seems to work fine now! :)

FYI, this was the backtrace:
```cpp
#0  0x00007ff61ff55320 in __cxa_begin_catch () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ff6214f7480 in sol::detail::static_trampoline<sol::usertype_metatable<T, std::integer_sequence<long unsigned int, I ...>, Tn ...>::real_index_call<Date::Absolute, {0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul, 11ul, 12ul, 13ul}, {const sol::call_construction&, sol::constructor_list<sol::types<const Date::Locale&>, sol::types<const Date::UTC&>, sol::types<const Date::Absolute&>, sol::types<int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int> >, sol::meta_function, bool (Date::Absolute::*)(const Date::Absolute&) const, sol::meta_function, bool (Date::Absolute::*)(const Date::Absolute&) const, char const (&)[4], sol::overload_set<Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Locale&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::UTC&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Absolute&)> >, char const (&)[5], sol::overload_set<Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Day&, Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Day&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Week&, Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Week&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Year::Month&, Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Year::Month&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Year::Day&, Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Year::Day&)> >, char const (&)[9], sol::overload_set<Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Day&, Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Day&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Week&, Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Week&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Year::Month&, Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Year::Month&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Year::Day&, Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Year::Day&)> >, char const (&)[5], sol::property_wrapper<Lua::State::initDate()::<lambda(const Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, int)> >, char const (&)[6], sol::property_wrapper<Lua::State::initDate()::<lambda(const Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, uint32_t)> >, char const (&)[4], sol::property_wrapper<Lua::State::initDate()::<lambda(const Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, uint32_t)> >, char const (&)[5], sol::property_wrapper<Lua::State::initDate()::<lambda(const Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, uint32_t)> >, char const (&)[7], sol::property_wrapper<Lua::State::initDate()::<lambda(const Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, uint32_t)> >, char const (&)[7], sol::property_wrapper<Lua::State::initDate()::<lambda(const Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, uint32_t)> >, char const (&)[11], sol::property_wrapper<Lua::State::initDate()::<lambda(const Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, uint32_t)> >, char const (&)[5], const sol::destructor_wrapper<void>&}> > (L=0x406e0378) at /usr/include/sol.hpp:3043
#2  sol::usertype_metatable<Date::Absolute, std::integer_sequence<long unsigned int, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul, 11ul, 12ul, 13ul>, const sol::call_construction&, sol::constructor_list<sol::types<const Date::Locale&>, sol::types<const Date::UTC&>, sol::types<const Date::Absolute&>, sol::types<int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int> >, sol::meta_function, bool (Date::Absolute::*)(const Date::Absolute&) const, sol::meta_function, bool (Date::Absolute::*)(const Date::Absolute&) const, char const (&)[4], sol::overload_set<Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Locale&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::UTC&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Absolute&)> >, char const (&)[5], sol::overload_set<Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Day&, Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Day&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Week&, Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Week&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Year::Month&, Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Year::Month&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Year::Day&, Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Year::Day&)> >, char const (&)[9], sol::overload_set<Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Day&, Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Day&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Week&, Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Week&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Year::Month&, Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Year::Month&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Year::Day&, Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, const Date::Relative::Year::Day&)> >, char const (&)[5], sol::property_wrapper<Lua::State::initDate()::<lambda(const Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, int)> >, char const (&)[6], sol::property_wrapper<Lua::State::initDate()::<lambda(const Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, uint32_t)> >, char const (&)[4], sol::property_wrapper<Lua::State::initDate()::<lambda(const Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, uint32_t)> >, char const (&)[5], sol::property_wrapper<Lua::State::initDate()::<lambda(const Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, uint32_t)> >, char const (&)[7], sol::property_wrapper<Lua::State::initDate()::<lambda(const Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, uint32_t)> >, char const (&)[7], sol::property_wrapper<Lua::State::initDate()::<lambda(const Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, uint32_t)> >, char const (&)[11], sol::property_wrapper<Lua::State::initDate()::<lambda(const Date::Absolute&)>, Lua::State::initDate()::<lambda(Date::Absolute&, uint32_t)> >, char const (&)[5], const sol::destructor_wrapper<void>&>::index_call(lua_State *) (L=0x406e0378) at /usr/include/sol.hpp:10537
#3  0x0000000000436e17 in lj_BC_FUNCC () at buildvm_x86.dasc:809
#4  0x00000000004160fb in lua_pcall (L=0x406e0378, nargs=0, nresults=-1, errfunc=2) at lj_api.c:1055
#5  0x000000000040414e in docall (L=0x406e0378, narg=0, clear=0) at luajit.c:121
```

C++ code:
```cpp
      date.new_usertype<Date::Absolute>("Absolute",
                                        sol::call_constructor, sol::constructors<
                                            sol::types<const Date::Locale&>,
                                            sol::types<const Date::UTC&>,
                                            sol::types<const Date::Absolute&>,
                                            sol::types<int, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t>
                                        >(),
                                       ...
```
