### ISSUE TITLE
Crash at state winding down

### ISSUE THREAD

**Issue by godexsoft** [ThePhD/sol2#964]
Thanks very much for the amazing work on sol3! loving the library. 

Ran into the following problem that i can't reproduce on my dev environment (MacOSX) but it happens on both clang/gcc builds on Linux (as well as in docker). Hope you will have some ideas how this could be fixed or why this even happens (and does not happen on MacOSX).

I'm trying to have two `contexts` both with their respective `sol::state`. One context is `staging` and i use it to compile all the lua scripts needed and throw an error if something went wrong. The other context is `master` which the `staging` context is swapped into once everything is ready.
The reload of staging happens from within a Lua function in a user script. However, the swap happens via a timer on a runloop on the next iteration of the loop. Since it's in a singlethreaded application i don't see why it would be a problem to nuke the lua state at that point and indeed on Mac it works just as expected. On linux however i get a crash with the following output in gdb: 

```
#0  0x00007f8fd66f70e8 in lua_rawgeti () from /usr/lib/liblua.so.5.3
#1  0x00007f8fd670bd71 in luaL_unref () from /usr/lib/liblua.so.5.3
#2  0x000055cde1068b04 in sol::stateless_reference::deref (this=0x55cde2788c70, L=0x55cde2753268) at /home/godexsoft/dev/krabby/lib/sol2/include/sol/reference.hpp:373
#3  0x000055cde1068acb in sol::basic_reference<false>::deref (this=0x55cde2788c70) at /home/godexsoft/dev/krabby/lib/sol2/include/sol/reference.hpp:448
#4  0x000055cde106c951 in sol::basic_reference<false>::~basic_reference (this=0x55cde2788c70) at /home/godexsoft/dev/krabby/lib/sol2/include/sol/reference.hpp:547
#5  0x000055cde1068a78 in sol::basic_object_base<sol::basic_reference<false> >::~basic_object_base (this=0x55cde2788c70)
    at /home/godexsoft/dev/krabby/lib/sol2/include/sol/object_base.hpp:33
#6  0x000055cde1071778 in sol::basic_object<sol::basic_reference<false> >::~basic_object (this=0x55cde2788c70) at /home/godexsoft/dev/krabby/lib/sol2/include/sol/object.hpp:35
#7  0x000055cde109c878 in sol::basic_function<sol::basic_reference<false>, false>::~basic_function (this=0x55cde2788c70)
    at /home/godexsoft/dev/krabby/lib/sol2/include/sol/unsafe_function.hpp:38
```

You can take a look at the code (it's opensource) here: https://github.com/godexsoft/krabby/blob/master/src/script.cpp#L18

The crash happens on line 40 in the file script.cpp.

Thanks in advance for any tips! 
Alex

**Comment by godexsoft** [comment]
Ok, i'm not sure what i was thinking but i suppose this fixes it:

```
~scripting_context() {
	router_.clear();	
	mountpoints_.clear();
	ws_handlers_.clear();
	disconnect_handlers_.clear();
}
```

I suppose i had to make sure i'm not still using anything from the lua state within my handlers.
Thanks again for the amazing effort on the library!
